<a href="https://colab.research.google.com/github/camoragaq/python-uoh/blob/main/Pauta_Conctrol_Catedra2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pauta Control Cátedra 2

6. Defina una classe Paciente() que tenga los atributos nombre, edad, y enfermedades; luego cree un objeto paciente con dichos atributos. Además, defina un método para agregar nuevas enfermedades y agregue enfermedad "covid":

In [8]:
class Paciente():
  def __init__(self, nombre, edad, enfermedades):
    self.nombre=nombre
    self.edad=edad
    self.enfermedades=enfermedades

  def agregarnuevaenf(self, nuevaenf):
    self.enfermedades.append(nuevaenf)


enfermedades=["migraña","bronquitis"]
juan=Paciente("Juan Perez","25",enfermedades)
juan.agregarnuevaenf("covid")
print(juan.enfermedades)

['migraña', 'bronquitis', 'covid']


7. Con el siguiente código aplicando concepto de Herencia, cree una instancia usando las clases para cambiar el password de su email:

In [11]:
class Mail():
  def __init__(self, email, clave):
    self.email=email
    self.clave=clave

  def checkemail(self):
    caracterBuscado="@"
    for c in self.email:
      if c==caracterBuscado:
        return True
      return False
    
  def resetemail(self, new):
    self.email=new 

class ResetCuenta(Mail):
    def cambiapassword(self, nuevopass):
      #if super().checkemail():
        self.clave=nuevopass

mail=ResetCuenta("carol@gmail","1234")
print(mail.clave)
mail.cambiapassword("hola34")
print(mail.clave)

1234
hola34


8. Dado el siguiente código:

In [13]:
class Auto():
    def bozina(self):
        print("Peep Peep!")

class Barco():
    def bozina(self):
        print("BMMMM BMMMM!")

class VehiculoAmfibio(Auto, Barco):
    def __init__(self):
        pass

Rayito = VehiculoAmfibio()
Rayito.bozina()

9. Identifique el o los errores en el siguiente código:

In [19]:
class Dog: 
    def __init__(my, name, yearBirth):
        my.name = name
        my.lenName = len(name)
        my.age = 2022-yearBirth 

a = Dog("Spike", "2016")

10. Dado el siguiente código, explique con palabras:

In [21]:
import csv

filename='data.csv'

f=open(filename)
reader=csv.reader(f)
header_row=next(reader)
print(header_row)
f.close()

11. Escriba un programa en Python

In [32]:
file=open("medicamentos.txt","r")
header=next(file)

for i in file:
  line=i.split("--")
  total=int(line[1])*int(line[2])
  print(line[0]+" "+str(total))

12. Dado el siguiente código usando la librería Matplotlib, dibuje el gráfico generado:

In [3]:
import matplotlib.pyplot as plt

x1=[10,20,30]
y1=[20,40,10]
x2=[10,20,30]
y2=[40,10,30]

plt.plot(x1,y1, color='blue')
plt.plot(x2,y2, color='red')

plt.show()

13. Cuál sería la suma acumulativa usando la función cumsum() de NumPy en el siguiente código?

In [15]:
a = np.array([1,2,3])
print(np.cumsum(a))

[1 3 6]


14. Cuál es la forma correcta para crear un arreglo NumPy?

In [18]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


15. Usando la función arange() escriba la instrucción para crear el siguiente arreglo:

In [19]:
a=np.arange(1,6)
print(a)

[1 2 3 4 5]


16. Cómo sumaría los arreglos a y b para generar la salida de abajo?

In [24]:
import numpy as np 
a=np.array([14,23,32,41])
b=np.array([5,4,3,2])
c=np.array([a+b])
#c=a+b
print(c)

[[19 27 35 43]]
